### ISSUE TITLE
Add basic instructions for visualizing a (big) GE2 file

### ISSUE THREAD

**Issue by hmparanjape** [beamteamco/davis#3]
We just tried viewing a large (1.9GB) GE2 file stack and had some confusion about how to view it. What function does left/right image have? Can you select a frame from the big GE2 to show in the left/right image?

**Comment by apetersen0** [comment]
Currently the best way to view a single image in the GE2 file is to unpack a single frame, and then load that image in the x-ray app (the file stem can be the file name of the image, minus the extension). The process this was designed so that after unpacking the GE2 file, you should get ~240 images. Ideally the naming scheme within the packing tool was set so it changes (split) stems after say 20-40 images. From within the x-ray app, you would then select the folder where you unpacked the images to and choose your desired stem. Clicking load would then open those 20-40 images corresponding to the file stem (20-40 due to memory restrictions). From here you can view the images incrementally by pressing the + and - buttons under image control, or type in which frame your interested in.

_edit_
The left/right image gives the ability to compare two images side by side. Some additional info you might find useful is right clicking next to an image, on the scale values (see image), will bring up a context menu that allows you to open the image in a separate resizable window.
![example1](https://cloud.githubusercontent.com/assets/13037285/8345374/58c84434-1aab-11e5-9436-848d5575f523.png)

**Comment by hmparanjape** [comment]
See detailed documentation here https://github.com/beamteamco/davis/wiki/davis-documentation-v-1.0.0
